# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\ALEXG\Documents\Ingeniería en Sistemas Computacionales\Semestre 4\Simulacion\Proyecto simulacion\simulacion\interfaces\ventana_ventas\Ingreso_datos_ventas.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1096, 678)
        Dialog.setStyleSheet("*{\n"
"font-family: Victor Mono;\n"
"}\n"
"\n"
"QPushButton{\n"
"border-radius: 5px;\n"
"background: #99b3ca;\n"
"font-size: 16px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background: #acc8e2;\n"
"font-weight:bold;\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QFrame#frame_aux{\n"
"background: #80a7ca;\n"
"border-radius: 10px;\n"
"font-size: 13px\n"
"}\n"
"\n"
"QFrame#frame_seleccion{\n"
"border-radius: 10px;\n"
"background: #80a7ca;\n"
"}\n"
"\n"
"QComboBox{\n"
"background: #e1e1e1;\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QFrame#tabla{\n"
"background: #e1e1e1;\n"
"border-radius: 12px;\n"
"}\n"
"\n"
"QLineEdit{\n"
"border-radius: 5px;\n"
"background: #e1e1e1;\n"
"}\n"
"\n"
"QFrame#frame{\n"
"background: #e1e1e1;\n"
"border-radius: 12px;\n"
"}\n"
"\n"
"QLabel#label_titulo{\n"
"    background: #99b3ca;\n"
"    border-radius: 10px;\n"
"    font-size: 24px;\n"
"}")
        self.tabla = QtWidgets.QTableWidget(Dialog)
        self.tabla.setGeometry(QtCore.QRect(30, 230, 711, 321))
        self.tabla.setObjectName("tabla")
        self.tabla.setColumnCount(0)
        self.tabla.setRowCount(0)
        self.btnmas = QtWidgets.QPushButton(Dialog)
        self.btnmas.setGeometry(QtCore.QRect(30, 560, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Victor Mono")
        font.setPointSize(-1)
        self.btnmas.setFont(font)
        self.btnmas.setObjectName("btnmas")
        self.Guardar = QtWidgets.QPushButton(Dialog)
        self.Guardar.setGeometry(QtCore.QRect(180, 600, 201, 51))
        self.Guardar.setObjectName("Guardar")
        self.btnmenos = QtWidgets.QPushButton(Dialog)
        self.btnmenos.setGeometry(QtCore.QRect(110, 560, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Victor Mono")
        font.setPointSize(-1)
        self.btnmenos.setFont(font)
        self.btnmenos.setObjectName("btnmenos")
        self.btniniciar = QtWidgets.QPushButton(Dialog)
        self.btniniciar.setGeometry(QtCore.QRect(430, 600, 201, 51))
        self.btniniciar.setObjectName("btniniciar")
        self.frame_aux = QtWidgets.QFrame(Dialog)
        self.frame_aux.setGeometry(QtCore.QRect(760, 250, 311, 241))
        self.frame_aux.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_aux.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_aux.setObjectName("frame_aux")
        self.label_3 = QtWidgets.QLabel(self.frame_aux)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 271, 20))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.iteraciones = QtWidgets.QLineEdit(self.frame_aux)
        self.iteraciones.setGeometry(QtCore.QRect(10, 50, 291, 31))
        self.iteraciones.setObjectName("iteraciones")
        self.btndatos = QtWidgets.QPushButton(self.frame_aux)
        self.btndatos.setGeometry(QtCore.QRect(10, 130, 291, 31))
        self.btndatos.setObjectName("btndatos")
        self.btncargar = QtWidgets.QPushButton(self.frame_aux)
        self.btncargar.setGeometry(QtCore.QRect(10, 190, 291, 28))
        self.btncargar.setObjectName("btncargar")
        self.toolButton = QtWidgets.QToolButton(Dialog)
        self.toolButton.setGeometry(QtCore.QRect(-10, -20, 1251, 711))
        self.toolButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\ALEXG\\Documents\\Ingeniería en Sistemas Computacionales\\Semestre 4\\Simulacion\\Proyecto simulacion\\simulacion\\interfaces\\ventana_ventas\\../images/bg (Grande).jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon)
        self.toolButton.setIconSize(QtCore.QSize(1400, 825))
        self.toolButton.setObjectName("toolButton")
        self.frame_seleccion = QtWidgets.QFrame(Dialog)
        self.frame_seleccion.setGeometry(QtCore.QRect(120, 160, 511, 61))
        self.frame_seleccion.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_seleccion.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_seleccion.setObjectName("frame_seleccion")
        self.tablas_opcion = QtWidgets.QComboBox(self.frame_seleccion)
        self.tablas_opcion.setGeometry(QtCore.QRect(160, 10, 341, 41))
        self.tablas_opcion.setObjectName("tablas_opcion")
        self.tablas_opcion.addItem("")
        self.tablas_opcion.addItem("")
        self.tablas_opcion.addItem("")
        self.label_2 = QtWidgets.QLabel(self.frame_seleccion)
        self.label_2.setGeometry(QtCore.QRect(30, 20, 111, 21))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(129, 40, 861, 80))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_titulo = QtWidgets.QLabel(self.frame)
        self.label_titulo.setGeometry(QtCore.QRect(10, 10, 841, 61))
        self.label_titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_titulo.setObjectName("label_titulo")
        self.toolButton.raise_()
        self.tabla.raise_()
        self.btnmas.raise_()
        self.Guardar.raise_()
        self.btnmenos.raise_()
        self.btniniciar.raise_()
        self.frame_aux.raise_()
        self.frame_seleccion.raise_()
        self.frame.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btnmas.setText(_translate("Dialog", "+"))
        self.Guardar.setText(_translate("Dialog", "Guardar datos"))
        self.btnmenos.setText(_translate("Dialog", "-"))
        self.btniniciar.setText(_translate("Dialog", "Iniciar simulación"))
        self.label_3.setText(_translate("Dialog", "Cantidad de semanas"))
        self.btndatos.setText(_translate("Dialog", "Guardar datos simulacion actual"))
        self.btncargar.setText(_translate("Dialog", "Cargar datos simulacion "))
        self.tablas_opcion.setItemText(0, _translate("Dialog", "Clientes de llegada"))
        self.tablas_opcion.setItemText(1, _translate("Dialog", "Estancia de los clientes"))
        self.tablas_opcion.setItemText(2, _translate("Dialog", "Tipo de alcohol comprado"))
        self.label_2.setText(_translate("Dialog", "Tabla"))
        self.label_titulo.setText(_translate("Dialog", "SIMULACIÓN SECCIÓN VENTAS"))
