# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\ALEXG\Documents\Ingeniería en Sistemas Computacionales\Semestre 4\Simulacion\Proyecto simulacion\simulacion\interfaces\ventanas_produccion\ingreso_datos_personal.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(756, 502)
        Dialog.setStyleSheet("*{\n"
"font-family: Victor Mono;\n"
"}\n"
"\n"
"QPushButton{\n"
"border-radius: 5px;\n"
"background: #99b3ca;\n"
"font-size: 16px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background: #acc8e2;\n"
"font-weight:bold;\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QFrame#tabla{\n"
"background: #e1e1e1;\n"
"border-radius: 12px;\n"
"}\n"
"\n"
"QFrame#frame_titulo_ventana{\n"
"background: #e1e1e1;\n"
"border-radius: 12px;\n"
"}\n"
"\n"
"QLabel#titulo{\n"
"    background: #99b3ca;\n"
"    border-radius: 5px;\n"
"    font-size: 24px;\n"
"}")
        self.tabla = QtWidgets.QTableWidget(Dialog)
        self.tabla.setGeometry(QtCore.QRect(20, 130, 711, 271))
        self.tabla.setObjectName("tabla")
        self.tabla.setColumnCount(0)
        self.tabla.setRowCount(0)
        self.btnmas = QtWidgets.QPushButton(Dialog)
        self.btnmas.setGeometry(QtCore.QRect(20, 410, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Victor Mono")
        font.setPointSize(-1)
        self.btnmas.setFont(font)
        self.btnmas.setObjectName("btnmas")
        self.btnmenos = QtWidgets.QPushButton(Dialog)
        self.btnmenos.setGeometry(QtCore.QRect(100, 410, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Victor Mono")
        font.setPointSize(-1)
        self.btnmenos.setFont(font)
        self.btnmenos.setObjectName("btnmenos")
        self.Guardar = QtWidgets.QPushButton(Dialog)
        self.Guardar.setGeometry(QtCore.QRect(260, 430, 201, 51))
        self.Guardar.setObjectName("Guardar")
        self.toolButton = QtWidgets.QToolButton(Dialog)
        self.toolButton.setGeometry(QtCore.QRect(-10, -10, 1001, 561))
        self.toolButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\ALEXG\\Documents\\Ingeniería en Sistemas Computacionales\\Semestre 4\\Simulacion\\Proyecto simulacion\\simulacion\\interfaces\\ventanas_produccion\\../images/bg (Grande).jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon)
        self.toolButton.setIconSize(QtCore.QSize(1920, 1080))
        self.toolButton.setObjectName("toolButton")
        self.frame_titulo_ventana = QtWidgets.QFrame(Dialog)
        self.frame_titulo_ventana.setGeometry(QtCore.QRect(60, 40, 621, 51))
        self.frame_titulo_ventana.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_titulo_ventana.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_titulo_ventana.setObjectName("frame_titulo_ventana")
        self.titulo = QtWidgets.QLabel(self.frame_titulo_ventana)
        self.titulo.setGeometry(QtCore.QRect(10, 10, 671, 81))
        self.titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo.setObjectName("titulo")
        self.toolButton.raise_()
        self.tabla.raise_()
        self.btnmas.raise_()
        self.btnmenos.raise_()
        self.Guardar.raise_()
        self.frame_titulo_ventana.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btnmas.setText(_translate("Dialog", "+"))
        self.btnmenos.setText(_translate("Dialog", "-"))
        self.Guardar.setText(_translate("Dialog", "Guardar"))
        self.titulo.setText(_translate("Dialog", "Ingreso de datos del personal"))
