# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\ALEXG\Documents\Ingeniería en Sistemas Computacionales\Semestre 4\Simulacion\Proyecto simulacion\simulacion\Generador-de-aleatorios-y-pruebas\metodos.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(545, 315)
        MainWindow.setStyleSheet("background-color: rgb(116, 138, 149);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.etiqueta_nombre = QtWidgets.QLabel(self.centralwidget)
        self.etiqueta_nombre.setGeometry(QtCore.QRect(190, 20, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Victor Mono SemiBold")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.etiqueta_nombre.setFont(font)
        self.etiqueta_nombre.setStyleSheet("color: rgb(255, 255, 255);")
        self.etiqueta_nombre.setObjectName("etiqueta_nombre")
        self.Opciones = QtWidgets.QComboBox(self.centralwidget)
        self.Opciones.setGeometry(QtCore.QRect(120, 150, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Victor Mono SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Opciones.setFont(font)
        self.Opciones.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"\n"
"")
        self.Opciones.setObjectName("Opciones")
        self.Opciones.addItem("")
        self.Opciones.addItem("")
        self.Opciones.addItem("")
        self.Opciones.addItem("")
        self.boton_aceptar = QtWidgets.QPushButton(self.centralwidget)
        self.boton_aceptar.setGeometry(QtCore.QRect(200, 250, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Victor Mono SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.boton_aceptar.setFont(font)
        self.boton_aceptar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.boton_aceptar.setObjectName("boton_aceptar")
        self.etiqueta_2 = QtWidgets.QLabel(self.centralwidget)
        self.etiqueta_2.setGeometry(QtCore.QRect(150, 70, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Victor Mono SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.etiqueta_2.setFont(font)
        self.etiqueta_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.etiqueta_2.setObjectName("etiqueta_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.etiqueta_nombre.setText(_translate("MainWindow", "Simulación"))
        self.Opciones.setItemText(0, _translate("MainWindow", "Metodo multiplicativo"))
        self.Opciones.setItemText(1, _translate("MainWindow", "Metodo mixto"))
        self.Opciones.setItemText(2, _translate("MainWindow", "Metodo de frecuencias"))
        self.Opciones.setItemText(3, _translate("MainWindow", "Komolgorov-Smirnoff"))
        self.boton_aceptar.setText(_translate("MainWindow", "Aceptar"))
        self.etiqueta_2.setText(_translate("MainWindow", "Programa integrador"))
