# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\ALEXG\Documents\Ingeniería en Sistemas Computacionales\Semestre 4\Simulacion\Proyecto simulacion\simulacion\pantalla_principal.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.setEnabled(True)
        mainWindow.resize(762, 430)
        mainWindow.setMinimumSize(QtCore.QSize(762, 430))
        mainWindow.setMaximumSize(QtCore.QSize(762, 430))
        mainWindow.setStyleSheet("@import url(\'https://fonts.googleapis.com/css2?family=Poppins&display=swap\');\n"
"\n"
"*{\n"
"font-family: Victor Mono;\n"
"    background-image: url(:/bacground/images/bg.jpg);\n"
"}\n"
"\n"
"QPushButton{\n"
"border-radius: 10px;\n"
"background: #99b3ca;\n"
"font-size: 19px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background: #acc8e2;\n"
"font-weight:bold;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QLabel#label1{\n"
"border-radius: 10px;\n"
"font-size: 22px;\n"
"background: #80a7ca;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnproduccion = QtWidgets.QPushButton(self.centralwidget)
        self.btnproduccion.setGeometry(QtCore.QRect(300, 290, 161, 81))
        self.btnproduccion.setObjectName("btnproduccion")
        self.btnventa = QtWidgets.QPushButton(self.centralwidget)
        self.btnventa.setGeometry(QtCore.QRect(60, 290, 161, 81))
        self.btnventa.setObjectName("btnventa")
        self.btnabastecimiento = QtWidgets.QPushButton(self.centralwidget)
        self.btnabastecimiento.setGeometry(QtCore.QRect(550, 290, 161, 81))
        self.btnabastecimiento.setObjectName("btnabastecimiento")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(180, 30, 431, 91))
        self.label1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label1.setAlignment(QtCore.Qt.AlignCenter)
        self.label1.setObjectName("label1")
        self.btnabastecimiento_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btnabastecimiento_2.setGeometry(QtCore.QRect(290, 160, 211, 81))
        self.btnabastecimiento_2.setObjectName("btnabastecimiento_2")
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "MainWindow"))
        self.btnproduccion.setText(_translate("mainWindow", "Produccion"))
        self.btnventa.setText(_translate("mainWindow", "Venta"))
        self.btnabastecimiento.setText(_translate("mainWindow", "Abastecimiento"))
        self.label1.setText(_translate("mainWindow", "SIMULACION PROYECTO FINAL MEZCALERA"))
        self.btnabastecimiento_2.setText(_translate("mainWindow", "Generacion aleatorios"))
import Source_rc
